# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/try-nbdev',
                'doc_host': 'https://wmelvin.github.io',
                'git_url': 'https://github.com/wmelvin/try-nbdev',
                'lib_path': 'try_nbdev'},
  'syms': {'try_nbdev.hello': {'try_nbdev.hello.say_hello': ('hello.html#say_hello', 'try_nbdev/hello.py')}}}