# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/try-nbdev',
                'doc_host': 'https://wmelvin.github.io',
                'git_url': 'https://github.com/wmelvin/try-nbdev',
                'lib_path': 'try_nbdev'},
  'syms': {'try_nbdev.core': {'try_nbdev.core.foo': ('core.html#foo', 'try_nbdev/core.py')}}}