# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_hello.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_hello.ipynb 2
def say_hello(to):
    "Say hello to somebody."
    return f"Hello, {to}."
